name: flutter_theme_manager
description: The Flutter Package to manage the themes efficiently.
version: 0.0.1
homepage: https://github.com/imihirpaldhikar/flutter_theme_manager

environment:
  sdk: ">=2.16.0-46.0.dev <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true