name: Dart Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter/master/x64/.pub-cache
          key: ${{ runner.OS }}-flutter-cache-master
          restore-keys: |
            ${{ runner.os }}-flutter-cache-master
            ${{ runner.os }}-flutter-cache-
            ${{ runner.os }}-
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: "master"
      - name: Install dependencies
        run: flutter pub get
      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .
      - name: Analyze project source
        run: flutter analyze
      - name: Run tests
        run: flutter test